create table SFLOW (
 ts bigint not null,
 agent varchar(64) not null,
 inport integer not null,
 outport integer not null,
 srcip varchar(64) not null,
 dstip varchar(64) not null,
 ipprocotol integer not null,
 srcport integer not null,
 dstport integer not null,
 tcp_flags integer not null,
 packet_size integer not null,
 ip_size integer not null,
 sampling_rate integer not null);
